routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::group(
    [
        'prefix' => \Mcamara\LaravelLocalization\Facades\LaravelLocalization::setLocale(),
        'middleware' => [ 'localeSessionRedirect', 'localizationRedirect', 'localeViewPath' ]
    ], function(){
        Auth::routes();
        Route::group([
            'as' => 'courses.',
        ], function () {
            Route::get('/courses', 'ProductController@list')->name('product.list');
            Route::get('/course/{product}', 'ProductController@show')->name('product.view');
        });
        Route::group([
            'as' => 'categories.',
        ], function () {
            Route::get('/category/{category}', 'CategoryController@show')->name('category.view');
            Route::get('/categories', 'CategoryController@list')->name('category.list');
        });
        Route::group([
            'as' => 'authors.',
        ], function () {
            Route::get('/authors', 'AuthorController@list')->name('author.list');
            Route::get('/author/{author}', 'AuthorController@show')->name('author.view');
        });
        Route::get('/', 'HomeController@index')->name('main');

        Route::get('change-password', 'User\ChangePasswordController@index')->middleware('auth')->name('change.password.form');
        Route::post('change-password', 'User\ChangePasswordController@store')->name('change.password')->middleware('auth');

        Route::get('user-courses', 'User\UserCoursesController@index')->middleware('auth')->name('user.course.list');
    });
//voting of courses
Route::post('/vote', 'ProductController@vote')->name('product.vote')->middleware('auth');
Route::post('/favorites', 'User\UserCoursesController@favorites')->name('usercourses.add')->middleware('auth');
Route::delete('/favorites-delete/{id}', 'User\UserCoursesController@delete')->name('usercourses.delete')->middleware('auth');


//admin area
\Illuminate\Support\Facades\Route::group(
    [
        'prefix' => 'admin',
        'as' => 'admin.',
        'middleware' => ['auth', 'can:admin-panel'],
        'namespace' => 'Admin',
    ],
    function (){
        \Illuminate\Support\Facades\Route::get('/', 'HomeController@index')->name('home');
        \Illuminate\Support\Facades\Route::resource('authors', 'AuthorController');
        \Illuminate\Support\Facades\Route::resource('users', 'UsersController');
        \Illuminate\Support\Facades\Route::resource('category', 'CategoryController');
        \Illuminate\Support\Facades\Route::resource('products', 'ProductController');


        \Illuminate\Support\Facades\Route::post('/category-videos/tree', 'CategoryVideosController@index')->name('category.videos.tree');
        \Illuminate\Support\Facades\Route::post('/category-videos/upDownPositionVideo', 'CategoryVideosController@upDownPositionVideoInCategory')->name('category.videos.updateposition');
        \Illuminate\Support\Facades\Route::post('/category-videos/getCategory', 'CategoryVideosController@getCategory')->name('category.videos.getcategory');
        \Illuminate\Support\Facades\Route::post('/category-videos/createCategory', 'CategoryVideosController@createCategory')->name('category.videos.create');
        \Illuminate\Support\Facades\Route::post('/category-videos/updateCategory', 'CategoryVideosController@updateCategory')->name('category.videos.update');
        \Illuminate\Support\Facades\Route::post('/category-videos/addVideoToCategory', 'CategoryVideosController@addVideoToCategory')->name('category.videos.addtocategory');
        \Illuminate\Support\Facades\Route::post('/category-videos/moveToAnotherCategory', 'CategoryVideosController@moveVideosToCategory')->name('category.videos.movetoanothercategory');
        \Illuminate\Support\Facades\Route::post('/category-videos/upDownPositionCategory', 'CategoryVideosController@upDownPositionCategory')->name('category.videos.updatepositioncategory');
        \Illuminate\Support\Facades\Route::post('/category-videos/deleteCategory', 'CategoryVideosController@deleteCategory')->name('category.videos.deletecategory');


        \Illuminate\Support\Facades\Route::get('/product/{id}/videos', 'VideoController@index')->name('videos.list');
        \Illuminate\Support\Facades\Route::post('/videos/upload', 'VideoController@upload')->name('videos.upload');
        \Illuminate\Support\Facades\Route::post('/videos/create', 'VideoController@create')->name('videos.create');
        \Illuminate\Support\Facades\Route::patch('/videos/update/{id}', 'VideoController@update')->name('videos.update');
        \Illuminate\Support\Facades\Route::post('/videos/update/source-link', 'VideoController@updateSourceLink')->name('videos.update.sourcelink');
        \Illuminate\Support\Facades\Route::get('/videos/edit/{id}', 'VideoController@edit')->name('videos.edit');
        \Illuminate\Support\Facades\Route::delete('/videos/', 'VideoController@delete')->name('videos.delete');
        \Illuminate\Support\Facades\Route::post('/videos/up', 'VideoController@up')->name('videos.up');
        \Illuminate\Support\Facades\Route::post('/videos/down', 'VideoController@down')->name('videos.down');
        \Illuminate\Support\Facades\Route::post('/videos/re-calc-position', 'VideoController@reCalcPosition')->name('videos.reCalcPosition');
        \Illuminate\Support\Facades\Route::get('/videos/renameVideosForm/{id}', 'VideoController@renameVideosForm')->name('videos.renameVideosForm');
        \Illuminate\Support\Facades\Route::post('/videos/renameVideos', 'VideoController@renameVideos')->name('videos.renameVideos');
        \Illuminate\Support\Facades\Route::post('/videos/remove-all-videos', 'VideoController@routeRemoveAllVideos')->name('videos.routeRemoveAllVideos');
        \Illuminate\Support\Facades\Route::post('/helper/translate', 'HelperController@translate')->name('helper.translate');

        \Illuminate\Support\Facades\Route::get('/course-materials/{courseId}', 'CourseMaterialsController@index')->name('course.materials.list');
        \Illuminate\Support\Facades\Route::get('/course-materials/create/{courseId}', 'CourseMaterialsController@create')->name('course.materials.create');
        \Illuminate\Support\Facades\Route::delete('/course-materials/delete/{id}', 'CourseMaterialsController@delete')->name('course.materials.delete');
        \Illuminate\Support\Facades\Route::post('/course-materials/file-upload', 'CourseMaterialsController@store')->name('course.materials.upload');
    }
);

app/Video.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Video extends Model
{
    protected $table = 'videos';
    public $timestamps = false;
    protected $fillable = [
        'title',
        'url',
        'product_id',
        'duration',
        'size',
        'position',
        'duration_full',
    ];

    public function toPlayerList(string $token): array
    {
        try {
            $duration = Product::seconds2human($this->duration);
        }catch (\Exception $exception){
            $duration = $this->duration;
        }
        return [
            "id" => $this->id,
      		"name" => $this->convertVideoTitle(),
      		"src" => env('FILE_STORAGE_URL_SERVER') . "/video/{$this->product_id}/$this->url?token=".$token,
      		"duration" => $duration,
            "time" => $this->duration,
            "course_id" => $this->product_id,
            'type' => 'video/mp4',
        ];
    }

    public function getSrcUrl(string $jwtToken)
    {
        return env('FILE_STORAGE_URL_SERVER') . "/video/{$this->product_id}/$this->url?token=".$jwtToken;
    }

    public function getSeconds2human()
    {
        try {
            $result = Product::seconds2human($this->duration);
        }catch (\Exception $exception){
            $result = $this->duration;
        }
        return $result;
    }

    public function convertVideoTitle()
    {
        return preg_replace('/\d{1,}|\#|\.mp4|\%0D\%0A|\%D\%A|\./', '',$this->title);
    }

    public function product()
    {
        return $this->belongsTo(Product::class, 'product_id', 'id');
    }
}

app/Http/Controllers/Admin/VideoController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Http\Requests\Admin\Video\RenameVideosRequest;
use App\Http\Requests\Admin\Video\UpdateRequest;
use App\Product;
use App\Rules\RenameVideosFilesNames;
use App\Services\CategoryVideoService;
use App\Services\VideoService;
use App\Video;
use Illuminate\Http\Request;
use App\Http\Resources\Admin\Videos as VideosResource;
use App\Http\Resources\Admin\VideosCollection;
use Illuminate\Support\Facades\Validator;
use Tymon\JWTAuth\Facades\JWTAuth;
use Tymon\JWTAuth\Facades\JWTFactory;

class VideoController extends Controller
{
    protected $videoService;
    protected $categoryVideos;

    public function __construct()
    {
        $this->videoService = new VideoService();
        $this->categoryVideos = new CategoryVideoService();
    }

    public function index($id){
        $videos = $this->videoService->getVideosList($id);
        $product = $this->loadProduct($id);
        $routeStorageUpload = env('FILE_STORAGE_URL_SERVER') . '/video/upload';
        $routeStorageVideo = env('FILE_STORAGE_URL_SERVER') . '/video/';
        $routeCreate = route('admin.videos.create');
        $routeDelete = route('admin.videos.delete');
        $routeUpPosition = route('admin.videos.up');
        $routeDownPosition = route('admin.videos.down');
        $routeReCalcPosition = route('admin.videos.reCalcPosition');
        $routeRemoveAllVideos = route('admin.videos.routeRemoveAllVideos');

        //get all tree structure of course
        $urlGetTree = route('admin.category.videos.tree');
        //get url for change position of video in category, move up/down video in list of category
        $urlUpDownPositionVideo = route('admin.category.videos.updateposition');
        //get category info, with all videos
        $urlGetCategory = route('admin.category.videos.getcategory');
        //category create url
        $urlCategoryCreate = route('admin.category.videos.create');
        //update category url
        $urlCategoryUpdate = route('admin.category.videos.update');
        //add video to category
        $urlAddVideoToCategory = route('admin.category.videos.addtocategory');
        //move videos fron one category to another category
        $moveToAnotherCategory = route('admin.category.videos.movetoanothercategory');
        //get link of source course
        $courseLinkSource = $product->source_link;
        //route to update source link of course
        $routeToUpdateSourceLinkOfCourse = route('admin.videos.update.sourcelink');
        //url for get course structure data
        $routeCourseStructureFromSource = env('FILE_STORAGE_URL_SERVER') . '/video/getcourseinfo';
        //route for update category position
        $urlUpDownCategoryPosition = route('admin.category.videos.updatepositioncategory');
        //url for delete category from course
        $urlDeleteCategory = route('admin.category.videos.deletecategory');

        //jwt token for access to NODEJS API
        $token = JWTAuth::fromUser(auth()->user());
        return view(
            'admin.videos.list',
            compact('urlDeleteCategory','urlUpDownCategoryPosition','routeCourseStructureFromSource','courseLinkSource','routeToUpdateSourceLinkOfCourse','moveToAnotherCategory','urlAddVideoToCategory','urlCategoryUpdate','urlCategoryCreate','urlGetCategory','urlUpDownPositionVideo','urlGetTree','token','videos', 'routeStorageUpload', 'routeCreate', 'routeStorageVideo', 'routeDelete', 'routeUpPosition', 'routeDownPosition', 'product', 'routeReCalcPosition', 'routeRemoveAllVideos')
        );
    }

    public function updateSourceLink(Request $request)
    {
        Product::query()
            ->where('id', $request->post('course_id'))
            ->update(['source_link'=>$request->post('source_link')]);
    }

    public function list(int $productId)
    {
        $product = $this->loadProduct($productId);
        return new VideosCollection($product->videos);
    }

    protected function loadProduct(int $id): Product
    {
        return Product::findOrFail($id);
    }

    public function edit($id)
    {
        $video = Video::findOrFail($id);
        return view('admin.videos.edit', compact('video'));
    }

    public function update(UpdateRequest $request, $id)
    {
        $video = Video::findOrFail($id);
        Video::where('id',$id)->update($request->validated());
        return redirect()->action('Admin\VideoController@index', $video->product_id)->with('success','Update Successfully');
    }

    public function delete(Request $request)
    {
        $result = $this->videoService->delete($request->get('id'));
        return response()->json($result);
    }

    /*
     * down video in position list
     */
    public function down(Request $request)
    {
        $this->videoService->downPosition($request->get('id'));
        return response()->json(['success'=>true], 200);
    }

    /*
     * up video file in position list
     */
    public function up(Request $request)
    {
        $this->videoService->upPosition($request->get('id'));
        return response()->json(['success'=>true], 200);
    }

    public function create(Request $request)
    {
        $video = $this->videoService->create(
            $request,
            $request->get('product_id')
        );
        return (new VideosResource($video))->response()->setStatusCode(201);
    }

    public function reCalcPosition(Request $request)
    {
        $this->videoService->reCalcPositions($request);
        return response()->json(['success'=>true], 200);
    }

    public function routeRemoveAllVideos(Request $request)
    {
        $this->videoService->removeAllVideos($request->get('id'));
        return response()->json(['success'=>true], 200);
    }

    public function renameVideosForm($id)
    {
        $course = Product::findOrFail($id);
        return view('admin.videos.rename_videos_names', compact('course'));
    }

    public function renameVideos(RenameVideosRequest $request)
    {
        /** @var Product $course */
        $course = $this->loadProduct($request->get('product_id'));
        $videos = $this->videoService->getVideosForCourseView($course->id);
        $validationRule = new RenameVideosFilesNames(count($videos));
        $this->validate($request, [
            'file_names' => [$validationRule]
        ]);
        $this->videoService->renameVideoFiles(
            $videos,
            $validationRule->getNames(),
            $course->id
        );
        return redirect()->back()->with('success','Update video files names -  Successfully updated');
    }
}

resources/views/admin/videos/edit.blade.php
@extends('layouts.app')

@section('content')
    <h2 style="margin-top: 12px;" class="text-center">Update video #{{$video->id}}</h2>
    <strong>Product:
        <br>{{$video->product->title_rus}}
        <br>{{$video->product->title_eng}}
    </strong>

    <div class="row">
        <form action="{{ route('admin.videos.update', $video->id) }}" method="POST" name="update_video">
            {{ csrf_field() }}
            @method('PATCH')

            <div class="row">
                <div class="col-md-12">
                    <div class="form-group">
                        <strong>Title</strong>
                        <input type="text" name="title" value="{{ $video->title }}" class="form-control" placeholder="Enter Title ">
                        <input type="hidden" name="product_id" value="{{ $video->product_id }}">
                        <span class="text-danger">{{ $errors->first('title') }}</span>
                    </div>
                </div>
                <div class="col-md-12">
                    <div class="form-group">
                        <strong>Url</strong>
                        <input type="text" name="url"  readonly class="form-control" value="{{ $video->url }}" placeholder="Enter Url">
                        <span class="text-danger">{{ $errors->first('url') }}</span>
                    </div>
                </div>
                <div class="col-md-12">
                    <div class="form-group">
                        <strong>Duration</strong>
                        <input type="text" name="duration"  readonly class="form-control" value="{{ $video->duration }}" placeholder="Enter duration">
                        <span class="text-danger">{{ $errors->first('duration') }}</span>
                    </div>
                </div>
                <div class="col-md-12">
                    <div class="form-group">
                        <strong>Size</strong>
                        <input type="text" name="size" readonly  class="form-control" value="{{ $video->size }}" placeholder="Enter size">
                        <span class="text-danger">{{ $errors->first('size') }}</span>
                    </div>
                </div>
                <div class="col-md-12">
                    <button type="submit" class="btn btn-primary">Submit</button>
                </div>
            </div>
        </form>
    </div>
@endsection

resources/views/admin/videos/list.blade.php
@extends('layouts.app')

@section('content')
    <div class="row">
        <div class="col-md-12">
            <label class="alert-success">
                <strong>Rus:</strong> {{$product->title_rus}} <br/>
                <strong>Eng:</strong> {{$product->title_eng}}<br>
            </label>
        </div>
        <div class="col-md-12">
            <a href="{{route('courses.product.view', $product)}}">
                <button class="btn btn-info">View page</button>
            </a>
            <a  href="{{route('admin.videos.renameVideosForm', $product->id)}}">
                <button class="btn btn-secondary btn-info ">Rename videos</button>
            </a>
            <strong>Total videos: {{ $product->count_video }}</strong>
            <strong>Total duration: {{ \App\Product::seconds2human($product->total_duration) }}</strong>
        </div>


        <div class="panel-body table-responsive pt-md-4">
            <nav>
                <div class="nav nav-tabs" id="nav-tab" role="tablist">
                    <a class="nav-item nav-link active" id="nav-home-tab" data-toggle="tab" href="#nav-home" role="tab" aria-controls="nav-home" aria-selected="true">CRUD Videos</a>
                    <a class="nav-item nav-link" id="nav-profile-tab" data-toggle="tab" href="#nav-profile" role="tab" aria-controls="nav-profile" aria-selected="false">Old Video upload</a>
                </div>
            </nav>

            <div class="tab-content" id="nav-tabContent">
                <div class="tab-pane fade show active" id="nav-home" role="tabpanel" aria-labelledby="nav-home-tab">
                    <div class="col-12">
                        <category-videos-control
                            :url_move_to_another_category="{{json_encode($moveToAnotherCategory)}}"
                            :url_up_down_position_video="{{json_encode($urlUpDownPositionVideo)}}"
                            :url_get_category="{{json_encode($urlGetCategory)}}"
                            :url_get_tree="{{json_encode($urlGetTree)}}"
                            :url_create_category="{{json_encode($urlCategoryCreate)}}"
                            :url_update_category="{{json_encode($urlCategoryUpdate)}}"
                            :url_update_source_link_of_course="{{json_encode($routeToUpdateSourceLinkOfCourse)}}"
                            :course_id = "{{json_encode($product->id)}}"
                            :show_with_out_category_videos="true"
                            :url_add_video_to_category="{{json_encode($urlAddVideoToCategory)}}"
                            :course_link="{{json_encode($courseLinkSource)}}"
                            :route_course_structure_from_source = "{{json_encode($routeCourseStructureFromSource)}}"
                            :url_up_down_category_position="{{json_encode($urlUpDownCategoryPosition)}}"
                            :url_delete_category="{{json_encode($urlDeleteCategory)}}"
                        >
                        </category-videos-control>
                    </div>
                </div>
                <div class="tab-pane fade" id="nav-profile" role="tabpanel" aria-labelledby="nav-profile-tab">
                    <videos-component
                        :route-up-position="{{json_encode($routeUpPosition)}}"
                        :route-down-position="{{json_encode($routeDownPosition)}}"
                        :route-storage-upload="{{json_encode($routeStorageUpload)}}"
                        :videos="{{json_encode($videos)}}"
                        :product-id="'{!! json_encode($product->id) !!}'"
                        :route-create="{{json_encode($routeCreate)}}"
                        :route-delete="{{json_encode($routeDelete)}}"
                        :route-storage-video="{{json_encode($routeStorageVideo)}}"
                        :route-re-calc-position="{{json_encode($routeReCalcPosition)}}"
                        :route-remove-all-videos="{{json_encode($routeRemoveAllVideos)}}"
                        :token="{{json_encode($token)}}"
                    ></videos-component>

                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/admin/videos/rename_videos_names.blade.php
@extends('layouts.app')

@section('content')
    <h2 style="margin-top: 12px;" class="text-center">Rename video files names in course #{{$course->id}}</h2>
    <strong>Product:
        <br>{{$course->title_rus}}
        <br>{{$course->title_eng}}
    </strong>
    <div class="row">
        <form action="{{ route('admin.videos.renameVideos', $course->id) }}" method="POST" name="update_video">
            {{ csrf_field() }}
            @method('POST')
            <div class="row">
                <div class="col-md-12">
                    <div class="form-group">
                        <label>New videos file names</label><br>
                        <textarea name="file_names" cols="45" rows="15"></textarea>
                        <input type="hidden" name="product_id" value="{{$course->id}}">
                    </div>
                </div>
                <div class="col-md-12">
                    <button type="submit" class="btn btn-primary">Update file names</button>
                </div>
            </div>
        </form>
    </div>
@endsection