routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::group(
    [
        'prefix' => \Mcamara\LaravelLocalization\Facades\LaravelLocalization::setLocale(),
        'middleware' => [ 'localeSessionRedirect', 'localizationRedirect', 'localeViewPath' ]
    ], function(){
        Auth::routes();
        Route::group([
            'as' => 'courses.',
        ], function () {
            Route::get('/courses', 'ProductController@list')->name('product.list');
            Route::get('/course/{product}', 'ProductController@show')->name('product.view');
        });
        Route::group([
            'as' => 'categories.',
        ], function () {
            Route::get('/category/{category}', 'CategoryController@show')->name('category.view');
            Route::get('/categories', 'CategoryController@list')->name('category.list');
        });
        Route::group([
            'as' => 'authors.',
        ], function () {
            Route::get('/authors', 'AuthorController@list')->name('author.list');
            Route::get('/author/{author}', 'AuthorController@show')->name('author.view');
        });
        Route::get('/', 'HomeController@index')->name('main');

        Route::get('change-password', 'User\ChangePasswordController@index')->middleware('auth')->name('change.password.form');
        Route::post('change-password', 'User\ChangePasswordController@store')->name('change.password')->middleware('auth');

        Route::get('user-courses', 'User\UserCoursesController@index')->middleware('auth')->name('user.course.list');
    });
//voting of courses
Route::post('/vote', 'ProductController@vote')->name('product.vote')->middleware('auth');
Route::post('/favorites', 'User\UserCoursesController@favorites')->name('usercourses.add')->middleware('auth');
Route::delete('/favorites-delete/{id}', 'User\UserCoursesController@delete')->name('usercourses.delete')->middleware('auth');


//admin area
\Illuminate\Support\Facades\Route::group(
    [
        'prefix' => 'admin',
        'as' => 'admin.',
        'middleware' => ['auth', 'can:admin-panel'],
        'namespace' => 'Admin',
    ],
    function (){
        \Illuminate\Support\Facades\Route::get('/', 'HomeController@index')->name('home');
        \Illuminate\Support\Facades\Route::resource('authors', 'AuthorController');
        \Illuminate\Support\Facades\Route::resource('users', 'UsersController');
        \Illuminate\Support\Facades\Route::resource('category', 'CategoryController');
        \Illuminate\Support\Facades\Route::resource('products', 'ProductController');


        \Illuminate\Support\Facades\Route::post('/category-videos/tree', 'CategoryVideosController@index')->name('category.videos.tree');
        \Illuminate\Support\Facades\Route::post('/category-videos/upDownPositionVideo', 'CategoryVideosController@upDownPositionVideoInCategory')->name('category.videos.updateposition');
        \Illuminate\Support\Facades\Route::post('/category-videos/getCategory', 'CategoryVideosController@getCategory')->name('category.videos.getcategory');
        \Illuminate\Support\Facades\Route::post('/category-videos/createCategory', 'CategoryVideosController@createCategory')->name('category.videos.create');
        \Illuminate\Support\Facades\Route::post('/category-videos/updateCategory', 'CategoryVideosController@updateCategory')->name('category.videos.update');
        \Illuminate\Support\Facades\Route::post('/category-videos/addVideoToCategory', 'CategoryVideosController@addVideoToCategory')->name('category.videos.addtocategory');
        \Illuminate\Support\Facades\Route::post('/category-videos/moveToAnotherCategory', 'CategoryVideosController@moveVideosToCategory')->name('category.videos.movetoanothercategory');
        \Illuminate\Support\Facades\Route::post('/category-videos/upDownPositionCategory', 'CategoryVideosController@upDownPositionCategory')->name('category.videos.updatepositioncategory');
        \Illuminate\Support\Facades\Route::post('/category-videos/deleteCategory', 'CategoryVideosController@deleteCategory')->name('category.videos.deletecategory');


        \Illuminate\Support\Facades\Route::get('/product/{id}/videos', 'VideoController@index')->name('videos.list');
        \Illuminate\Support\Facades\Route::post('/videos/upload', 'VideoController@upload')->name('videos.upload');
        \Illuminate\Support\Facades\Route::post('/videos/create', 'VideoController@create')->name('videos.create');
        \Illuminate\Support\Facades\Route::patch('/videos/update/{id}', 'VideoController@update')->name('videos.update');
        \Illuminate\Support\Facades\Route::post('/videos/update/source-link', 'VideoController@updateSourceLink')->name('videos.update.sourcelink');
        \Illuminate\Support\Facades\Route::get('/videos/edit/{id}', 'VideoController@edit')->name('videos.edit');
        \Illuminate\Support\Facades\Route::delete('/videos/', 'VideoController@delete')->name('videos.delete');
        \Illuminate\Support\Facades\Route::post('/videos/up', 'VideoController@up')->name('videos.up');
        \Illuminate\Support\Facades\Route::post('/videos/down', 'VideoController@down')->name('videos.down');
        \Illuminate\Support\Facades\Route::post('/videos/re-calc-position', 'VideoController@reCalcPosition')->name('videos.reCalcPosition');
        \Illuminate\Support\Facades\Route::get('/videos/renameVideosForm/{id}', 'VideoController@renameVideosForm')->name('videos.renameVideosForm');
        \Illuminate\Support\Facades\Route::post('/videos/renameVideos', 'VideoController@renameVideos')->name('videos.renameVideos');
        \Illuminate\Support\Facades\Route::post('/videos/remove-all-videos', 'VideoController@routeRemoveAllVideos')->name('videos.routeRemoveAllVideos');
        \Illuminate\Support\Facades\Route::post('/helper/translate', 'HelperController@translate')->name('helper.translate');

        \Illuminate\Support\Facades\Route::get('/course-materials/{courseId}', 'CourseMaterialsController@index')->name('course.materials.list');
        \Illuminate\Support\Facades\Route::get('/course-materials/create/{courseId}', 'CourseMaterialsController@create')->name('course.materials.create');
        \Illuminate\Support\Facades\Route::delete('/course-materials/delete/{id}', 'CourseMaterialsController@delete')->name('course.materials.delete');
        \Illuminate\Support\Facades\Route::post('/course-materials/file-upload', 'CourseMaterialsController@store')->name('course.materials.upload');
    }
);

app/Http/Controllers/Admin/ProductController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Author;
use App\Category;
use App\Http\Controllers\Controller;
use App\Http\Requests\Admin\Product\CreateRequest;
use App\Http\Requests\Admin\Product\UpdateRequest;
use App\Product;
use App\Services\AuthorService;
use App\Services\CategoryService;
use App\Services\ProductService;
use Illuminate\Http\Request;
use Illuminate\Support\Str;

class ProductController extends Controller
{
    protected $productService;
    protected $authorService;
    protected $categoryService;

    public function __construct()
    {
        $this->productService = new ProductService();
        $this->authorService = new AuthorService();
        $this->categoryService = new CategoryService();
    }

    public function index(Request $request)
    {
        $query = Product::query()->with(['author', 'categories']);
        if ($request->has('category_id') && !empty($request->get('category_id'))) {
            $query->whereHas('categories', function ($query) use ($request) {
                $query->where('category_id', $request->get('category_id'));
            });
        }
        if ($request->has('title') && !empty($request->get('title'))) {
            $query->where(function ($query) use ($request) {
                $query->orWhere('title_rus', 'LIKE','%'.$request->get('title').'%')
                    ->orWhere('title_eng', 'LIKE','%'.$request->get('title').'%');
            });
        }
        if ($request->has('author_id') && !empty($request->get('author_id'))) {
            $query->where('author_id', $request->get('author_id'));
        }
        $products = $query
            ->orderBy('id','desc')
            ->paginate(10)
            ->appends($request->toArray())
            ->setPath('products');

        $categories = Category::getNotRoot();

        return view('admin.products.list',compact(['products', 'request', 'categories']));
    }

    public function create()
    {
        $authors = $this->authorService->getAll();
        $categoriesAll = $this->categoryService->getNotRoots();
        $langs = Product::getLangList();
        $product = new Product();
        return view('admin.products.create',compact(['authors', 'categoriesAll', 'product', 'langs']));
    }

    public function store(CreateRequest $request)
    {
        $this->productService->create($request);
        return redirect()->route('admin.products.index')->with('success','Create Successfully');
    }

    public function show($id)
    {
        $data =  Product::findOrFail($id);
        return view('admin.products.show',compact(['data']));
    }

    public function edit($id)
    {
        $product = Product::with('categories')->findOrFail($id);
        $authors = $this->authorService->getAll();
        $categoriesAll = $this->categoryService->getNotRoots();
        $langs = Product::getLangList();
        return view('admin.products.edit',compact(['product', 'authors', 'categoriesAll', 'langs']));
    }

    public function update(UpdateRequest $request, $id)
    {
        $this->productService->update($request, Product::findOrFail($id));
        return redirect()->route('admin.products.index')->with('success','Update Successfully');
    }

    public function destroy($id)
    {
        //remove all videos from remote server
        $this->productService->delete($id);

        return redirect()->back()->with('success','Delete Successfully');
    }
}

app/Http/Controllers/ProductController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\SearchRequest;
use App\Http\Requests\User\UserRegisteredCourses\CreateRequest;
use App\Product;
use App\Services\CourseMaterialsService;
use App\Services\ProductService;
use App\Services\VideoService;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Str;
use Artesaos\SEOTools\Facades\SEOMeta;

class ProductController extends Controller
{
    public function show(Product $product)
    {
        $product::with(['author', 'categories', 'userCanLike']);

        SEOMeta::setTitle($product->getTitle());
        SEOMeta::setDescription(Str::words(strip_tags($product->getDescription()), 40));
        SEOMeta::addMeta('article:published_time', $product->created_at->toW3cString(), 'property');
        SEOMeta::addMeta('article:section', $product->getCategoriesListByComa(), 'property');
        SEOMeta::addMeta('og:type', "article", 'property');
        SEOMeta::addMeta('og:title', $product->getTitle(), 'property');
        SEOMeta::addMeta('og:description', Str::words(strip_tags($product->getDescription()), 40), 'property');
        SEOMeta::addMeta('og:url', request()->root(), 'property');

        $videos = [];
        $materialsOfCourse = [];
        if (Auth::check()) {
            $videoService = new VideoService();
            $videoTree = $videoService->getTreeCategoriesVideosCoursePage($product->id);
            //temp fix
            if(empty($videoTree['categories'])){
                $videoTree['categories'][] = ['title'=>'All videos', 'videos'=>$videoTree['otherVideos']];
                $videoTree['otherVideos'] = [];
            }
            $materials = new CourseMaterialsService();
            $materialsOfCourse = $materials->getFilesOfCourse($product->id);
        }
        $productService = new ProductService();
        $similarCourses = $productService->getSimilarCourses($product->id, 5);


        return view('products.show', compact('videoTree','product', 'videos', 'materialsOfCourse', 'similarCourses'));
    }

    public function vote(Request $request)
    {
        $exists = DB::table('likes_history')
            ->where('user_id', auth()->user()->id)
            ->where('product_id', $request->get('product_id'))
            ->exists();

        if (!$exists) {
            $product = Product::with('categories', 'author')->findOrFail($request->get('product_id'));
            if ($request->get('action') == "likes") {
                $product->author()->increment('rating');
                $product->categories()->increment('rating');
                DB::table('products')
                    ->where('id', $request->get('product_id'))
                    ->update([
                        'likes' => DB::raw('likes + 1'),
                        'rating' => DB::raw('rating + 1'),
                    ]);
            } else {
                $product->author()->decrement('rating');
                $product->categories()->decrement('rating');
                DB::table('products')
                    ->where('id', $request->get('product_id'))
                    ->update([
                        'unlikes' => DB::raw('unlikes + 1'),
                        'rating' => DB::raw('rating - 1'),
                    ]);
            }
            DB::table('likes_history')
                ->insert([
                    'product_id' => $request->get('product_id'),
                    'user_id' => auth()->user()->id,
                ]);
        }
        return response()->json(['success' => true]);
    }

    public function list(SearchRequest $request)
    {
        SEOMeta::setTitle(__('Video tutorials, courses, tutorials'));
        SEOMeta::addMeta('og:type', "article", 'property');
        SEOMeta::addMeta('og:title', __('Video tutorials, courses, tutorials'), 'property');
        SEOMeta::addMeta('og:url', request()->root(), 'property');

        $productService = new ProductService();

        $products = $productService->searchCourses($request);

        return view('products.list', compact('products', 'request'));
    }
}

resources/views/products/card-list.blade.php
<div class="col d-flex py-2" style="padding-right: 5px; padding-left: 5px;">
    <div class="card w-100" data-container="body" data-toggle="popover" data-delay='{ "show": 100, "hide": 250 }' data-placement="right" data-trigger="hover" data-html="true"
         data-content='
            <div class="alert alert-primary">
                <span class="pull-center">
                    {{__('Duration')}} : {{ \App\Product::seconds2human($product->total_duration) }}
                </span><br>
                 <span class="pull-center">
                     {{__('Videos')}} : {{ $product->count_video }}
                 </span><br>
                 <span class="pull-center">
                    {{__('Author')}} : {{ $product->author->name }}
                 </span><br>
                 <span class="pull-center">
                    {{__('Language')}} : {{ __($product->getLangLabel()) }}
                 </span><br>
                <span class="pull-center">
                    {{ __('Rating') }} :
                    <span class="fa fa-thumbs-up" >  {{$product->likes}} </span>
                    <span class="fa fa-thumbs-down" >  {{$product->unlikes}} </span>
                </span>
                <hr>
                {{ Str::words(strip_tags($product->getDescription()), 30, ' ...') }}
            </div>'
        >
        <a href="{{route('courses.product.view', $product)}}">
            <img src="data:image/{{$product->img}}" class="card-img-top rounded" alt="{{$product->getTitle()}}">
        </a>
        <div class="card-body text-center">
            <h5 class="card-title">
                <a href="{{route('courses.product.view', $product)}}">
                    {{$product->getTitle()}}
                </a>
                @can('admin-panel')
                    <a class="btn-sm btn-danger" href="{{route('admin.products.edit', $product->id)}}">
                        (Edit)
                    </a>
                @endcan
            </h5>
        </div>
    </div>
</div>

resources/views/products/list.blade.php
@extends('layouts.app')

@section('content')

    <h2>{{__('Video tutorials, courses, tutorials')}}</h2>

    @include('products.searchform')

    <div class="row row-cols-1 row-cols-md-5">

        @foreach($products as $product)
            @include('products.card-list')
        @endforeach

    </div>

    {!! $products->links() !!}

@endsection

resources/views/products/rating.blade.php
@auth()
    <span class="pull-center">
        <span class="badge badge-light">
            <like-unlike-component
                :likes="'{!! json_encode($product->likes) !!}'"
                :unlikes="'{!! json_encode($product->unlikes) !!}'"
                :product_id="'{!! json_encode($product->id) !!}'"
                :disable="'{!! json_encode(false) !!}'"
            >
            </like-unlike-component>
        </span>
    </span>
@endauth
@guest()
    <span class="pull-center">
        <span class="badge badge-light">
            <button class="fa fa-thumbs-up likePost btn btn-outline-primary btn-sm" disabled>  {{$product->likes}} </button>
            <button class="fa fa-thumbs-down likePost btn btn-outline-primary btn-sm" disabled>  {{$product->unlikes}} </button>
        </span>
    </span>
@endguest

resources/views/products/searchform.blade.php
<div class="row ">
    <div class="col-sm-10 offset-sm-1 text-center">
        <form class="form-inline justify-content-center " method="get" action="{{route('courses.product.list')}}">
            <div class="input-group col-4">
                <input type="text" value="{{old('query', request('query'))}}" minlength="3" class=" text-center form-control form-control-lg" id="inlineFormInputName2" name="query" placeholder="..." maxlength="120" required>
            </div>
            <button type="submit" class="btn btn-success">{{__('Search')}}</button>
        </form>
    </div>
</div>

resources/views/products/show.blade.php
@extends('layouts.app')

@section('content')
    <div class="card text-center">
        <div class="card-header">
            <h2>
                @can('admin-panel')
                    <a class="btn btn-danger" href="{{route('admin.products.edit', $product->id)}}">(Edit)</a>
                @endcan
                {{$product->getTitle()}}
            </h2>
        </div>
        <div class="card-body">

            @auth
                <video-player-component :videos="{{json_encode($videoTree)}}"></video-player-component>
            @endauth

            @guest
                <div class="card border-success mx-auto" style="max-width: 18rem">
                    <div class="card-header">
                        <h4 class="alert-heading">{{__('Access deny')}}</h4>
                    </div>
                    <div class="card-body text-danger">
                        <h5 class="card-title">{{__('Only registered users can watch videos')}}</h5>
                        <p class="card-text">
                            <a class="nav-pills btn-lg btn-primary" href="{{route('register')}}">
                                {{__('Register')}}
                            </a>
                        </p>
                    </div>
                </div>
                <br>
            @endguest
            <h5 class="card-title">
                <strong>{{__('Categories')}}</strong>:
                @foreach($product->categories as $category)
                    <a class="btn btn-sm btn-success" href="{{route('categories.category.view', $category)}}"> {{$category->title}}</a>
                @endforeach
            </h5>
            <p>
                <span class="badge badge-light pull-center">
                    <strong class="card-list-product-options">
                        {{__('Language')}} : {{ __($product->getLangLabel()) }}
                    </strong>
                </span>
                    <span class="badge badge-pill pull-center">
                    <strong class="card-list-product-options">
                        {{__('Duration')}} : {{ \App\Product::seconds2human($product->total_duration) }}
                    </strong>
                </span>
                    <span class="badge badge-pill pull-center">
                    <strong class="card-list-product-options">
                        {{__('Videos')}} : {{ $product->count_video }}
                    </strong>
                </span>
                    <span class="badge badge-pill pull-center">
                    <strong class="card-list-product-options">
                        <a class="btn-primary" href="{{ route('authors.author.view', $product->author)  }}">
                            {{__('Author')}} : {{ $product->author->name }}
                        </a>
                    </strong>
                </span>
                <span class="badge badge-pill">
                    @include('products.rating')
                </span>
                @auth()
                    <span class="badge badge-pill pull-center">
                        <course-favorite :disable="'{!! json_encode($product->isFavorite()) !!}'"
                                         :label="'{!! __('To favorites') !!}'"
                                         :course_id="'{!! json_encode($product->id) !!}'"
                        ></course-favorite>
                    </span>
                @endauth
            </p>


            <button class="btn btn-primary" type="button" data-toggle="collapse" data-target="#collapseExample" aria-expanded="false" aria-controls="collapseExample">
                {{__('Description of course')}}
            </button>
            <div class="collapse" id="collapseExample">
                <div class="card card-body">
                    {!! strip_tags($product->getDescription()) !!}
                </div>
            </div>

            <button class="btn btn-primary" type="button" data-toggle="collapse" data-target="#collapseComments" aria-expanded="false" aria-controls="collapseComments">
                {{__('Comments')}}
            </button>
            <div class="collapse" id="collapseComments">
                <div class="card card-body">
                    @comments([
                    'model' => $product,
                    ])
                </div>
            </div>


            @auth
                @if(!$materialsOfCourse->isEmpty())
                    <button class="btn btn-primary" type="button" data-toggle="collapse" data-target="#collapseMaterials" aria-expanded="false" aria-controls="collapseMaterials">
                        {{__('Materials')}}
                    </button>
                    <div class="collapse" id="collapseMaterials">
                        <br>
                        @foreach($materialsOfCourse as $material)
                            <strong>
                                <a class="alert-dark" href="/materials/{{$material->url}}">
                                    {{__('Download materials')}}
                                </a> <br>
                            </strong>
                        @endforeach
                    </div>
                @endif


            @endauth
        </div>

        <div class="card-footer text-muted">
            <h3 class="text-center ">{{__('Similar courses')}}</h3>
            <div class="row row-cols-1 row-cols-md-5">
                @foreach($similarCourses as $product)
                    @include('products.card-list')
                @endforeach
            </div>
        </div>
    </div>
@endsection