routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::group(
    [
        'prefix' => \Mcamara\LaravelLocalization\Facades\LaravelLocalization::setLocale(),
        'middleware' => [ 'localeSessionRedirect', 'localizationRedirect', 'localeViewPath' ]
    ], function(){
        Auth::routes();
        Route::group([
            'as' => 'courses.',
        ], function () {
            Route::get('/courses', 'ProductController@list')->name('product.list');
            Route::get('/course/{product}', 'ProductController@show')->name('product.view');
        });
        Route::group([
            'as' => 'categories.',
        ], function () {
            Route::get('/category/{category}', 'CategoryController@show')->name('category.view');
            Route::get('/categories', 'CategoryController@list')->name('category.list');
        });
        Route::group([
            'as' => 'authors.',
        ], function () {
            Route::get('/authors', 'AuthorController@list')->name('author.list');
            Route::get('/author/{author}', 'AuthorController@show')->name('author.view');
        });
        Route::get('/', 'HomeController@index')->name('main');

        Route::get('change-password', 'User\ChangePasswordController@index')->middleware('auth')->name('change.password.form');
        Route::post('change-password', 'User\ChangePasswordController@store')->name('change.password')->middleware('auth');

        Route::get('user-courses', 'User\UserCoursesController@index')->middleware('auth')->name('user.course.list');
    });
//voting of courses
Route::post('/vote', 'ProductController@vote')->name('product.vote')->middleware('auth');
Route::post('/favorites', 'User\UserCoursesController@favorites')->name('usercourses.add')->middleware('auth');
Route::delete('/favorites-delete/{id}', 'User\UserCoursesController@delete')->name('usercourses.delete')->middleware('auth');


//admin area
\Illuminate\Support\Facades\Route::group(
    [
        'prefix' => 'admin',
        'as' => 'admin.',
        'middleware' => ['auth', 'can:admin-panel'],
        'namespace' => 'Admin',
    ],
    function (){
        \Illuminate\Support\Facades\Route::get('/', 'HomeController@index')->name('home');
        \Illuminate\Support\Facades\Route::resource('authors', 'AuthorController');
        \Illuminate\Support\Facades\Route::resource('users', 'UsersController');
        \Illuminate\Support\Facades\Route::resource('category', 'CategoryController');
        \Illuminate\Support\Facades\Route::resource('products', 'ProductController');


        \Illuminate\Support\Facades\Route::post('/category-videos/tree', 'CategoryVideosController@index')->name('category.videos.tree');
        \Illuminate\Support\Facades\Route::post('/category-videos/upDownPositionVideo', 'CategoryVideosController@upDownPositionVideoInCategory')->name('category.videos.updateposition');
        \Illuminate\Support\Facades\Route::post('/category-videos/getCategory', 'CategoryVideosController@getCategory')->name('category.videos.getcategory');
        \Illuminate\Support\Facades\Route::post('/category-videos/createCategory', 'CategoryVideosController@createCategory')->name('category.videos.create');
        \Illuminate\Support\Facades\Route::post('/category-videos/updateCategory', 'CategoryVideosController@updateCategory')->name('category.videos.update');
        \Illuminate\Support\Facades\Route::post('/category-videos/addVideoToCategory', 'CategoryVideosController@addVideoToCategory')->name('category.videos.addtocategory');
        \Illuminate\Support\Facades\Route::post('/category-videos/moveToAnotherCategory', 'CategoryVideosController@moveVideosToCategory')->name('category.videos.movetoanothercategory');
        \Illuminate\Support\Facades\Route::post('/category-videos/upDownPositionCategory', 'CategoryVideosController@upDownPositionCategory')->name('category.videos.updatepositioncategory');
        \Illuminate\Support\Facades\Route::post('/category-videos/deleteCategory', 'CategoryVideosController@deleteCategory')->name('category.videos.deletecategory');


        \Illuminate\Support\Facades\Route::get('/product/{id}/videos', 'VideoController@index')->name('videos.list');
        \Illuminate\Support\Facades\Route::post('/videos/upload', 'VideoController@upload')->name('videos.upload');
        \Illuminate\Support\Facades\Route::post('/videos/create', 'VideoController@create')->name('videos.create');
        \Illuminate\Support\Facades\Route::patch('/videos/update/{id}', 'VideoController@update')->name('videos.update');
        \Illuminate\Support\Facades\Route::post('/videos/update/source-link', 'VideoController@updateSourceLink')->name('videos.update.sourcelink');
        \Illuminate\Support\Facades\Route::get('/videos/edit/{id}', 'VideoController@edit')->name('videos.edit');
        \Illuminate\Support\Facades\Route::delete('/videos/', 'VideoController@delete')->name('videos.delete');
        \Illuminate\Support\Facades\Route::post('/videos/up', 'VideoController@up')->name('videos.up');
        \Illuminate\Support\Facades\Route::post('/videos/down', 'VideoController@down')->name('videos.down');
        \Illuminate\Support\Facades\Route::post('/videos/re-calc-position', 'VideoController@reCalcPosition')->name('videos.reCalcPosition');
        \Illuminate\Support\Facades\Route::get('/videos/renameVideosForm/{id}', 'VideoController@renameVideosForm')->name('videos.renameVideosForm');
        \Illuminate\Support\Facades\Route::post('/videos/renameVideos', 'VideoController@renameVideos')->name('videos.renameVideos');
        \Illuminate\Support\Facades\Route::post('/videos/remove-all-videos', 'VideoController@routeRemoveAllVideos')->name('videos.routeRemoveAllVideos');
        \Illuminate\Support\Facades\Route::post('/helper/translate', 'HelperController@translate')->name('helper.translate');

        \Illuminate\Support\Facades\Route::get('/course-materials/{courseId}', 'CourseMaterialsController@index')->name('course.materials.list');
        \Illuminate\Support\Facades\Route::get('/course-materials/create/{courseId}', 'CourseMaterialsController@create')->name('course.materials.create');
        \Illuminate\Support\Facades\Route::delete('/course-materials/delete/{id}', 'CourseMaterialsController@delete')->name('course.materials.delete');
        \Illuminate\Support\Facades\Route::post('/course-materials/file-upload', 'CourseMaterialsController@store')->name('course.materials.upload');
    }
);

app/Category.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Collection;

class Category extends Model
{
    protected $table = 'categories';

    protected $fillable = [
        'title',
        'url',
        'parent_id',
        'rating',
    ];

    /**
     * Get the route key for the model.
     *
     * @return string
     */
    public function getRouteKeyName()
    {
        return 'url';
    }

    public static function getCategoriesList(): array
    {
        return Category::all(['id','title', 'parent_id'])
            ->sortBy('parent_id')
            ->sortBy('title')
            ->all();
    }

    public static function getRoots()
    {
        $roots = Category::all(['id', 'parent_id', 'title'])
            ->where('parent_id', null)
            ->toArray();
        return $roots;
    }

    public static function getNotRoot()
    {
        $roots = Category::with('childrens')
            ->where('parent_id', '!=', null)
            ->orderBy('title')
            ->get();
        return $roots;
    }

    public static function getCategoriesAll(int $limit = 100)
    {
        return Category::all()->take($limit)->sortBy('title')->all();
    }

    public function root()
    {
        return $this->belongsTo(Category::class, 'parent_id', 'id');
    }

    public function childrens()
    {
        return $this->hasMany(Category::class, 'parent_id', 'id');
    }

    public function products()
    {
        return $this->belongsToMany(Product::class, 'category_product', 'category_id', 'product_id');
    }
}

app/Http/Controllers/Admin/CategoryController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Category;
use App\Http\Requests\Admin\Category\CreateRequest;
use App\Http\Requests\Admin\Category\UpdateRequest;
use App\Services\CategoryService;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Str;

class CategoryController extends Controller
{
    protected $categoryService;

    public function __construct()
    {
        $this->categoryService = new CategoryService();
    }

    public function index()
    {
        $categories = Category::orderBy('id','desc')->paginate(50)->setPath('category');
        return view('admin.categories.list',compact(['categories']));
    }

    public function create()
    {
        $roots = $this->categoryService->getRoots();
        return view('admin.categories.create', ['category'=> new Category(), 'roots'=>$roots]);
    }

    public function store(CreateRequest $request)
    {
        $data = $request->validated();
        Category::create($data);
        //flush cache
        $this->categoryService->clearCache();
        return redirect()->action('Admin\CategoryController@index')->with('success','Create Successfully');
    }

    public function show($id)
    {
        $category =  Category::findOrFail($id);
        return view('admin.categories.show',compact(['category']));
    }

    public function edit(Category $category)
    {
        $roots = $this->categoryService->getRoots();
        return view('admin.categories.edit',compact(['category', 'roots']));
    }

    public function update(UpdateRequest $request, $id)
    {
        $valid = $request->validated();
        if(empty($valid['url'])){
            $valid['url'] = Str::slug($valid['title']);
        }
        Category::where('id',$id)->update($valid);
        //flush cache
        $this->categoryService->clearCache();

        return redirect()->action('Admin\CategoryController@index')->with('success','Update Successfully');
    }

//    public function destroy($id)
//    {
//        DB::table('category_product')->where('category_id', $id)->delete();
//        Category::where('id',$id)->delete();
//        return redirect()->back()->with('success','Delete Successfully');
//    }
}

app/Http/Controllers/CategoryController.php
<?php

namespace App\Http\Controllers;

use App\Category;
use Artesaos\SEOTools\Facades\SEOMeta;
use Illuminate\Http\Request;
use Illuminate\Support\Str;
use Mcamara\LaravelLocalization\Facades\LaravelLocalization;

class CategoryController extends Controller
{
    public function show(Category $category)
    {
        $pageTitle = __('Video tutorials, courses, tutorials by category') . ' : ' . $category->title;
        SEOMeta::setTitle($pageTitle);
        SEOMeta::addMeta('article:published_time', $category->created_at->toW3cString(), 'property');
        SEOMeta::addMeta('og:title', $pageTitle, 'property');
        SEOMeta::addMeta('og:type', "article", 'property');
        SEOMeta::addMeta('og:url', request()->root(), 'property');

        $products = $category->products()->with(['author'])->publish()->sortRating()->paginate(10);
        return view('categories.show', compact('category', 'products'));
    }

    public function list()
    {
        $pageTitle = "Категории курсов";
        if(LaravelLocalization::getCurrentLocale() !== "ru"){
            $pageTitle = "Course categories";
        }
        SEOMeta::setTitle($pageTitle);
        SEOMeta::addMeta('og:title', $pageTitle, 'property');
        SEOMeta::addMeta('og:type', "article", 'property');
        SEOMeta::addMeta('og:url', request()->root(), 'property');

        $categories = Category::where('parent_id', '!=', null)->orderBy('title')->get();
        return view('categories.list', compact('categories'));
    }
}

resources/views/admin/categories/create.blade.php
@extends('layouts.app')

@section('content')
    <h2 style="margin-top: 12px;" class="text-center">Add category</h2>
    <div class="row">
        <form action="{{ route('admin.category.store') }}" method="POST" name="add_category">
            {{ csrf_field() }}
            <div class="row">
                <div class="col-md-12">
                    <div class="form-group">
                        <strong>Parent Category</strong>
                        <select id="parent-id" multiple class="form-control{{ $errors->has('parent_id') ? ' is-invalid' : '' }}" name="parent_id">
                            <option value="">Empty</option>
                            @foreach ($roots as $root))
                                <option value="{{$root['id']}}">{{$root['title']}}</option>
                            @endforeach;
                        </select>
                    </div>
                </div>
                <div class="col-md-12">
                    <div class="form-group">
                        <strong>Title</strong>
                        <input type="text" value="{{ old('title', $category->title) }}" name="title" class="form-control" placeholder="Enter Title ">
                        <span class="text-danger">{{ $errors->first('title') }}</span>
                    </div>
                </div>
                <div class="col-md-12">
                    <div class="form-group">
                        <strong>Url</strong>
                        <input type="text" name="url" class="form-control" value="{{ old('url', $category->url) }}" placeholder="Enter Url">
                        <span class="text-danger">{{ $errors->first('url') }}</span>
                    </div>
                </div>
                <div class="col-md-12">
                    <button type="submit" class="btn btn-primary">Submit</button>
                </div>
            </div>
        </form>
    </div>
@endsection

resources/views/admin/categories/edit.blade.php
@extends('layouts.app')

@section('content')
    <h2 style="margin-top: 12px;" class="text-center">Update category #{{$category->id}}</h2>
    <div class="row">
        <form action="{{ route('admin.category.update', $category->id) }}" method="POST" name="update_category">
            {{ csrf_field() }}
            @method('PATCH')
            <div class="col-md-12">
                <div class="form-group">
                    <strong>Parent Category</strong>
                    <select id="parent-id" multiple class="form-control{{ $errors->has('parent_id') ? ' is-invalid' : '' }}" name="parent_id">
                        <option value="">Empty</option>
                        @foreach ($roots as $root))
                            <option {{ $root['id'] == old('parent_id', $category->parent_id) ? ' selected' : '' }} value="{{$root['id']}}" >{{$root['title']}}</option>
                        @endforeach;
                    </select>
                </div>
            </div>

            <div class="row">
                <div class="col-md-12">
                    <div class="form-group">
                        <strong>Title</strong>
                        <input type="text" name="title" value="{{ $category->title }}" class="form-control" placeholder="Enter Title ">
                        <span class="text-danger">{{ $errors->first('title') }}</span>
                    </div>
                </div>
                <div class="col-md-12">
                    <div class="form-group">
                        <strong>Url</strong>
                        <input type="text" name="url" class="form-control" value="{{ $category->url }}" placeholder="Enter Url">
                        <span class="text-danger">{{ $errors->first('url') }}</span>
                    </div>
                </div>
                <div class="col-md-12">
                    <button type="submit" class="btn btn-primary">Submit</button>
                </div>
            </div>
        </form>
    </div>
@endsection

resources/views/admin/categories/list.blade.php
@extends('layouts.app')

@section('content')
    <div class="row">
        <div class="col-12">
            <table class="table table-bordered">
                <thead>
                <tr>
                    <th scope="col">Id</th>
                    <th scope="col">Root</th>
                    <th scope="col">Title</th>
                    <th scope="col">Rating</th>
                    <th >Url</th>
                    <td>
                        Action
                        <a href="{{ route('admin.category.create') }}" class="btn btn-success mb-2">Create</a>
                    </td>
                </tr>
                </thead>
                <tbody>
                @foreach($categories as $category)
                    <tr>
                        <td>{{ $category->id }}</td>
                        <td>{{ empty($category->root->title) ? "": $category->root->title }}</td>
                        <td>{{ $category->title }}</td>
                        <td>{{ $category->rating }}</td>
                        <td>{{ $category->url }}</td>
                        <td>
                            <form action="{{ route('admin.category.destroy', $category->id)}}" method="post">
                                <a href="{{ route('admin.category.edit', $category)}}" class="btn btn-sm btn-primary">Edit</a>
                                {{ csrf_field() }}
                                @method('DELETE')
{{--                                <button class="btn btn-sm btn-danger" type="submit">Delete</button>--}}
                            </form>
                        </td>
                    </tr>
                    @endforeach
                </tbody>
            </table>
            {!! $categories->links() !!}
        </div>
    </div>
@endsection