routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::group(
    [
        'prefix' => \Mcamara\LaravelLocalization\Facades\LaravelLocalization::setLocale(),
        'middleware' => [ 'localeSessionRedirect', 'localizationRedirect', 'localeViewPath' ]
    ], function(){
        Auth::routes();
        Route::group([
            'as' => 'courses.',
        ], function () {
            Route::get('/courses', 'ProductController@list')->name('product.list');
            Route::get('/course/{product}', 'ProductController@show')->name('product.view');
        });
        Route::group([
            'as' => 'categories.',
        ], function () {
            Route::get('/category/{category}', 'CategoryController@show')->name('category.view');
            Route::get('/categories', 'CategoryController@list')->name('category.list');
        });
        Route::group([
            'as' => 'authors.',
        ], function () {
            Route::get('/authors', 'AuthorController@list')->name('author.list');
            Route::get('/author/{author}', 'AuthorController@show')->name('author.view');
        });
        Route::get('/', 'HomeController@index')->name('main');

        Route::get('change-password', 'User\ChangePasswordController@index')->middleware('auth')->name('change.password.form');
        Route::post('change-password', 'User\ChangePasswordController@store')->name('change.password')->middleware('auth');

        Route::get('user-courses', 'User\UserCoursesController@index')->middleware('auth')->name('user.course.list');
    });
//voting of courses
Route::post('/vote', 'ProductController@vote')->name('product.vote')->middleware('auth');
Route::post('/favorites', 'User\UserCoursesController@favorites')->name('usercourses.add')->middleware('auth');
Route::delete('/favorites-delete/{id}', 'User\UserCoursesController@delete')->name('usercourses.delete')->middleware('auth');


//admin area
\Illuminate\Support\Facades\Route::group(
    [
        'prefix' => 'admin',
        'as' => 'admin.',
        'middleware' => ['auth', 'can:admin-panel'],
        'namespace' => 'Admin',
    ],
    function (){
        \Illuminate\Support\Facades\Route::get('/', 'HomeController@index')->name('home');
        \Illuminate\Support\Facades\Route::resource('authors', 'AuthorController');
        \Illuminate\Support\Facades\Route::resource('users', 'UsersController');
        \Illuminate\Support\Facades\Route::resource('category', 'CategoryController');
        \Illuminate\Support\Facades\Route::resource('products', 'ProductController');


        \Illuminate\Support\Facades\Route::post('/category-videos/tree', 'CategoryVideosController@index')->name('category.videos.tree');
        \Illuminate\Support\Facades\Route::post('/category-videos/upDownPositionVideo', 'CategoryVideosController@upDownPositionVideoInCategory')->name('category.videos.updateposition');
        \Illuminate\Support\Facades\Route::post('/category-videos/getCategory', 'CategoryVideosController@getCategory')->name('category.videos.getcategory');
        \Illuminate\Support\Facades\Route::post('/category-videos/createCategory', 'CategoryVideosController@createCategory')->name('category.videos.create');
        \Illuminate\Support\Facades\Route::post('/category-videos/updateCategory', 'CategoryVideosController@updateCategory')->name('category.videos.update');
        \Illuminate\Support\Facades\Route::post('/category-videos/addVideoToCategory', 'CategoryVideosController@addVideoToCategory')->name('category.videos.addtocategory');
        \Illuminate\Support\Facades\Route::post('/category-videos/moveToAnotherCategory', 'CategoryVideosController@moveVideosToCategory')->name('category.videos.movetoanothercategory');
        \Illuminate\Support\Facades\Route::post('/category-videos/upDownPositionCategory', 'CategoryVideosController@upDownPositionCategory')->name('category.videos.updatepositioncategory');
        \Illuminate\Support\Facades\Route::post('/category-videos/deleteCategory', 'CategoryVideosController@deleteCategory')->name('category.videos.deletecategory');


        \Illuminate\Support\Facades\Route::get('/product/{id}/videos', 'VideoController@index')->name('videos.list');
        \Illuminate\Support\Facades\Route::post('/videos/upload', 'VideoController@upload')->name('videos.upload');
        \Illuminate\Support\Facades\Route::post('/videos/create', 'VideoController@create')->name('videos.create');
        \Illuminate\Support\Facades\Route::patch('/videos/update/{id}', 'VideoController@update')->name('videos.update');
        \Illuminate\Support\Facades\Route::post('/videos/update/source-link', 'VideoController@updateSourceLink')->name('videos.update.sourcelink');
        \Illuminate\Support\Facades\Route::get('/videos/edit/{id}', 'VideoController@edit')->name('videos.edit');
        \Illuminate\Support\Facades\Route::delete('/videos/', 'VideoController@delete')->name('videos.delete');
        \Illuminate\Support\Facades\Route::post('/videos/up', 'VideoController@up')->name('videos.up');
        \Illuminate\Support\Facades\Route::post('/videos/down', 'VideoController@down')->name('videos.down');
        \Illuminate\Support\Facades\Route::post('/videos/re-calc-position', 'VideoController@reCalcPosition')->name('videos.reCalcPosition');
        \Illuminate\Support\Facades\Route::get('/videos/renameVideosForm/{id}', 'VideoController@renameVideosForm')->name('videos.renameVideosForm');
        \Illuminate\Support\Facades\Route::post('/videos/renameVideos', 'VideoController@renameVideos')->name('videos.renameVideos');
        \Illuminate\Support\Facades\Route::post('/videos/remove-all-videos', 'VideoController@routeRemoveAllVideos')->name('videos.routeRemoveAllVideos');
        \Illuminate\Support\Facades\Route::post('/helper/translate', 'HelperController@translate')->name('helper.translate');

        \Illuminate\Support\Facades\Route::get('/course-materials/{courseId}', 'CourseMaterialsController@index')->name('course.materials.list');
        \Illuminate\Support\Facades\Route::get('/course-materials/create/{courseId}', 'CourseMaterialsController@create')->name('course.materials.create');
        \Illuminate\Support\Facades\Route::delete('/course-materials/delete/{id}', 'CourseMaterialsController@delete')->name('course.materials.delete');
        \Illuminate\Support\Facades\Route::post('/course-materials/file-upload', 'CourseMaterialsController@store')->name('course.materials.upload');
    }
);

app/CourseMaterials.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class CourseMaterials extends Model
{
    protected $table = 'course_materials';
    public $timestamps = false;
    protected $fillable = [
        'course_id',
        'file',
        'url',
        'size',
    ];
}

app/Http/Controllers/Admin/CourseMaterialsController.php
<?php

namespace App\Http\Controllers\Admin;

use App\CourseMaterials;
use App\Http\Controllers\Controller;
use App\Http\Requests\Admin\CourseMaterials\CreateRequest;
use App\Product;
use App\Services\CourseMaterialsService;
use Illuminate\Http\Request;

class CourseMaterialsController extends Controller
{
    protected $courseMaterialsService;

    public function __construct()
    {
        $this->courseMaterialsService = new CourseMaterialsService();
    }

    public function index($courseId)
    {
        $course = Product::findOrFail($courseId);
        $files = $this->courseMaterialsService->getFilesOfCourse($courseId);
        return view('admin.course_materials.list',compact(['files', 'course']));
    }

    public function create($courseId)
    {
        $course = new CourseMaterials();
        $course->course_id = $courseId;
        return view('admin.course_materials.create',compact(['course']));
    }

    public function store(CreateRequest $request)
    {
        $model = $this->courseMaterialsService->create($request);
        return redirect()->route('admin.course.materials.list', $model->course_id)->with('success','Create Successfully');
    }

    public function delete(int $id)
    {
        $this->courseMaterialsService->delete($id);

        return redirect()->back()->with('success','Delete Successfully');
    }
}

resources/views/admin/course_materials/create.blade.php
@extends('layouts.app')

@section('content')
    <h2 style="margin-top: 12px;" class="text-center">Add file to course</h2>
    <div class="row">
        <form action="{{ route('admin.course.materials.upload') }}" enctype="multipart/form-data" method="POST" name="upload_material">
            {{ csrf_field() }}
            <div class="row">
                <div class="col-md-12">
                    <div class="form-group">
                        <strong>File:</strong>
                        <input type="file" name="file" class="form-control" placeholder="Select file ">
                        <span class="text-danger">{{ $errors->first('file') }}</span>
                        <input type="hidden" name="course_id" value="{{$course->course_id}}">
                    </div>
                </div>
                <div class="col-md-12">
                    <button type="submit" class="btn btn-primary">Upload</button>
                </div>
            </div>
        </form>
    </div>
@endsection

resources/views/admin/course_materials/list.blade.php
@extends('layouts.app')

@section('content')
    <div class="row">
        <div class="col-12">

            <h4>
                {{$course->title_rus}} <br>
                {{$course->title_eng}}
            </h4>

            <table class="table table-bordered">
                <thead>
                <tr>
                    <th scope="col">Id</th>
                    <th scope="col">File</th>
                    <th scope="col">Url</th>
                    <th scope="col">Size</th>
                    <td>
                        Action
                        <a href="{{ route('admin.course.materials.create', $course->id) }}" class="btn btn-success mb-2">Create</a>
                    </td>
                </tr>
                </thead>
                <tbody>
                @foreach($files as $file)
                    <tr>
                        <td>{{ $file->id }}</td>
                        <td>{{ empty($file->file) ? "": $file->file }}</td>
                        <td>{{ $file->url }}</td>
                        <td>{{ $file->size }}</td>
                        <td>
                            <form action="{{ route('admin.course.materials.delete', $file->id)}}" method="post">
                                {{ csrf_field() }}
                                @method('DELETE')
                                <button class="btn btn-sm btn-danger" type="submit">Delete</button>
                            </form>
                        </td>
                    </tr>
                @endforeach
                </tbody>
            </table>
        </div>
    </div>
@endsection